services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.11
    container_name: jellyfin
    ports:
      - "${JELLYFIN_PORT}:8096"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/health"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 30s
    networks:
      - home
    volumes:
      - "${JELLYFIN_CACHE}:/cache"
      - "${JELLYFIN_CONFIG}:/config"
      - "${JELLYFIN_MEDIA}:/media"
    group_add:
      - "992" #`getent group render`
  kavita:
    image: jvmilazz0/kavita:0.9.0.2
    container_name: kavita
    volumes:
      - "${KAVITA_DATA}:/books"
      - "${KAVITA_CONFIG}:/kavita/config"
    environment:
      - TZ=${TZ}
    ports:
      - "${KAVITA_PORT}:5000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 30s
    networks:
      - home

  caddy:
    image: adrianbaraka/caddy-dnsexit:2.11.2
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    #network_mode: host
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      CADDY_ADMIN: "0.0.0.0:2019"
      TZ: ${TZ}
      DNS_EXIT_TOKEN: ${DNS_EXIT_TOKEN}
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL}
    volumes:
      - ./files/Caddyfile:/etc/caddy/Caddyfile
      - ${CADDY_DATA}:/data
      - ${CADDY_CONFIG}:/config
    healthcheck:
      # create an endpoint in caddyfile
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 30s
    networks:
      - home
networks:
  home:
    external: true
