services:
  drawio:
    image: jgraph/drawio:29.6.10
    container_name: drawio
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
    environment:
      - TZ=Africa/Nairobi
    ports:
      - "9081:8080"
      - "9443:8443"
    restart: unless-stopped
