services:
    tailscale:
      image: tailscale/tailscale:v1.96.5
      container_name: tailscale
      hostname: homelab
      network_mode: host
      environment:
        - TS_AUTHKEY=${TS_AUTHKEY}
        - TS_STATE_DIR=/var/lib/tailscale
        - TS_USERSPACE=false
        - TS_ACCEPT_DNS=true
        - TZ=${TZ}
        - TS_EXTRA_ARGS=--advertise-exit-node
      volumes:
        - ${TS_STATE_DIR}:/var/lib/tailscale
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      restart: unless-stopped
      healthcheck:
        test: [ "CMD-SHELL", "tailscale status --peers=false" ]
        interval: 1m
        retries: 3
        start_period: 30s