package subs

import "time"

// autogenerated from https://mholt.github.io/json-to-go/

type MkvmergeRes struct {
	Attachments []any `json:"attachments"`
	Chapters    []struct {
		NumEntries int `json:"num_entries"`
	} `json:"chapters"`
	Container struct {
		Properties struct {
			ContainerType         int       `json:"container_type"`
			DateLocal             time.Time `json:"date_local"`
			DateUtc               time.Time `json:"date_utc"`
			Duration              int64     `json:"duration"`
			IsProvidingTimestamps bool      `json:"is_providing_timestamps"`
			MuxingApplication     string    `json:"muxing_application"`
			SegmentUID            string    `json:"segment_uid"`
			TimestampScale        int       `json:"timestamp_scale"`
			WritingApplication    string    `json:"writing_application"`
		} `json:"properties"`
		Recognized bool   `json:"recognized"`
		Supported  bool   `json:"supported"`
		Type       string `json:"type"`
	} `json:"container"`
	Errors                      []any  `json:"errors"`
	FileName                    string `json:"file_name"`
	GlobalTags                  []any  `json:"global_tags"`
	IdentificationFormatVersion int    `json:"identification_format_version"`
	TrackTags                   []any  `json:"track_tags"`
	Tracks                      []struct {
		Codec      string `json:"codec"`
		ID         int    `json:"id"`
		Properties struct {
			CodecID            string `json:"codec_id"`
			CodecPrivateData   string `json:"codec_private_data"`
			CodecPrivateLength int    `json:"codec_private_length"`
			DefaultDuration    int    `json:"default_duration"`
			DefaultTrack       bool   `json:"default_track"`
			DisplayDimensions  string `json:"display_dimensions"`
			DisplayUnit        int    `json:"display_unit"`
			EnabledTrack       bool   `json:"enabled_track"`
			ForcedTrack        bool   `json:"forced_track"`
			Language           string `json:"language"`
			LanguageIetf       string `json:"language_ietf"`
			MinimumTimestamp   int    `json:"minimum_timestamp"`
			NumIndexEntries    int    `json:"num_index_entries"`
			Number             int    `json:"number"`
			Packetizer         string `json:"packetizer"`
			PixelDimensions    string `json:"pixel_dimensions"`
			UID                int64  `json:"uid"`
		} `json:"properties,omitempty"`
		Type        string `json:"type"`
		Properties0 struct {
			AudioChannels          int    `json:"audio_channels"`
			AudioSamplingFrequency int    `json:"audio_sampling_frequency"`
			CodecID                string `json:"codec_id"`
			CodecPrivateData       string `json:"codec_private_data"`
			CodecPrivateLength     int    `json:"codec_private_length"`
			DefaultDuration        int    `json:"default_duration"`
			DefaultTrack           bool   `json:"default_track"`
			EnabledTrack           bool   `json:"enabled_track"`
			ForcedTrack            bool   `json:"forced_track"`
			Language               string `json:"language"`
			LanguageIetf           string `json:"language_ietf"`
			MinimumTimestamp       int    `json:"minimum_timestamp"`
			NumIndexEntries        int    `json:"num_index_entries"`
			Number                 int    `json:"number"`
			UID                    int64  `json:"uid"`
		} `json:"properties,omitempty"`
		Properties1 struct {
			CodecID            string `json:"codec_id"`
			CodecPrivateLength int    `json:"codec_private_length"`
			DefaultTrack       bool   `json:"default_track"`
			EnabledTrack       bool   `json:"enabled_track"`
			Encoding           string `json:"encoding"`
			ForcedTrack        bool   `json:"forced_track"`
			Language           string `json:"language"`
			LanguageIetf       string `json:"language_ietf"`
			MinimumTimestamp   int    `json:"minimum_timestamp"`
			NumIndexEntries    int    `json:"num_index_entries"`
			Number             int    `json:"number"`
			TextSubtitles      bool   `json:"text_subtitles"`
			UID                int64  `json:"uid"`
		} `json:"properties"`
	} `json:"tracks"`
	Warnings []any `json:"warnings"`
}

type MkvmergeErrorRes struct {
	Errors   []string `json:"errors"`
	Warnings []string `json:"warnings"`
}
